name: proyecto-java
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest 
        steps:

            - name: Comprobar y obtener codigo 
              uses: actions/checkout@v4

            - name: Crear carpeta en AWS 
              uses: appleboy/ssh-action@v1
              with:
                    host: ${{ secrets.IP_SERVER }}
                    username: ${{ secrets.USERNAME  }}
                    key: ${{ secrets.KEY }}
                    port: ${{ secrets.PORT }}
                    script: |
                            mkdir -p /home/ubuntu/java
            


            - name: Sincronizar proyecto en el servidor 
              uses: burnett01/rsync-deployments@7.0.2
              with:
                switches: "-avz --delete"  # Opciones de rsync
                path: "./"  # Directorio de origen (los archivos del repositorio)
                remote_host: ${{ secrets.IP_SERVER }}  # Dirección IP del servidor
                remote_user: ${{ secrets.USERNAME }}  # Usuario SSH en el servidor
                remote_path: "/home/ubuntu/java/"  # Ruta de destino en el servidor
                remote_key: ${{ secrets.KEY }}  # Clave SSH para autenticar
                remote_port: ${{ secrets.PORT }}  # Puerto SSH (si es distinto del predeterminado 22)


            - name: Levantar docker con docker compose 
              uses: appleboy/ssh-action@v1
              with:
                host:  ${{ secrets.IP_SERVER }}
                username: ${{ secrets.USERNAME  }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: |
                        cd /home/ubuntu/java
                        docker compose down 
                        docker compose up -d --build 
              
